# Generated by Django 4.2.13 on 2024-06-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="kasyno",
            new_name="casino",
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="participants",
            new_name="users",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="other_place",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="place",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="meetings.place"),
        ),
    ]
