# Generated by Django 4.2.13 on 2024-06-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_dailycoins"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="kosa_coins",
            new_name="coins",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="kosa_points",
            new_name="points",
        ),
        migrations.AlterField(
            model_name="dailycoins",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="daily_coins", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
