# Generated by Django 4.2.13 on 2024-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_kosa_coins_user_coins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
