# Generated by Django 4.2.13 on 2024-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variables",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
            ],
        ),
    ]
