# Generated by Django 4.2.13 on 2024-06-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycoins",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
