# Generated by Django 4.2.13 on 2024-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_dailycoins_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="coins",
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name="quest",
            name="exp",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="quest",
            name="points",
            field=models.IntegerField(default=10),
        ),
    ]
