# Generated by Django 4.2.13 on 2024-06-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_quest_coins_quest_exp_quest_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatchNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("text", models.TextField(help_text="You can use markdown here")),
                ("version", models.CharField(blank=True, max_length=40)),
                ("major", models.BooleanField(default=False)),
            ],
        ),
    ]
