# Generated by Django 4.2.13 on 2024-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_patchnotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patchnotes",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
