# Generated by Django 4.2.13 on 2024-07-01 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_patchnotes_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patchnotes",
            options={"verbose_name_plural": "Patch Notes"},
        ),
    ]
