# Generated by Django 4.2.13 on 2024-06-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Weight of the symbol, the higher number the bigger chance of it rolling')),
                ('value', models.PositiveIntegerField(default=1, help_text="Value of the symbol, if user rolls a line of them, this is the amount it'sgona be multiplied by")),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='lines',
        ),
        migrations.AddField(
            model_name='spin',
            name='chosen_lines',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='symbols',
            field=models.ManyToManyField(related_name='games', to='casino.symbol'),
        ),
    ]
