# Generated by Django 4.2.13 on 2024-07-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0004_alter_cardgame_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardgame",
            name="deck",
            field=models.JSONField(
                default=[
                    "2 of clubs",
                    "2 of hearts",
                    "2 of diamonds",
                    "2 of spades",
                    "3 of clubs",
                    "3 of hearts",
                    "3 of diamonds",
                    "3 of spades",
                    "4 of clubs",
                    "4 of hearts",
                    "4 of diamonds",
                    "4 of spades",
                    "5 of clubs",
                    "5 of hearts",
                    "5 of diamonds",
                    "5 of spades",
                    "6 of clubs",
                    "6 of hearts",
                    "6 of diamonds",
                    "6 of spades",
                    "7 of clubs",
                    "7 of hearts",
                    "7 of diamonds",
                    "7 of spades",
                    "8 of clubs",
                    "8 of hearts",
                    "8 of diamonds",
                    "8 of spades",
                    "9 of clubs",
                    "9 of hearts",
                    "9 of diamonds",
                    "9 of spades",
                    "10 of clubs",
                    "10 of hearts",
                    "10 of diamonds",
                    "10 of spades",
                    "J of clubs",
                    "J of hearts",
                    "J of diamonds",
                    "J of spades",
                    "Q of clubs",
                    "Q of hearts",
                    "Q of diamonds",
                    "Q of spades",
                    "K of clubs",
                    "K of hearts",
                    "K of diamonds",
                    "K of spades",
                    "A of clubs",
                    "A of hearts",
                    "A of diamonds",
                    "A of spades",
                ]
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="symbols",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="casino.symbol"
            ),
        ),
    ]
