# Generated by Django 4.2.13 on 2024-07-02 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0006_highcard_delete_cardgame"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spin",
            old_name="won",
            new_name="has_won",
        ),
        migrations.RemoveField(
            model_name="spin",
            name="amount",
        ),
        migrations.AddField(
            model_name="spin",
            name="reward",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="spin",
            name="chosen_lines",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
