# Generated by Django 4.2.13 on 2024-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0007_rename_won_spin_has_won_remove_spin_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highcard",
            name="deck",
        ),
        migrations.RemoveField(
            model_name="highcard",
            name="user",
        ),
        migrations.AddField(
            model_name="highcard",
            name="last_card",
            field=models.CharField(default="", max_length=20),
        ),
    ]
