# Generated by Django 4.2.13 on 2024-07-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("casino", "0008_remove_highcard_deck_remove_highcard_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highcard",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
