# Generated by Django 4.2.13 on 2024-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0009_highcard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
