# Generated by Django 4.2.13 on 2024-07-02 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0010_alter_game_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spin",
            old_name="reward",
            new_name="amount",
        ),
    ]
