# Generated by Django 4.2.13 on 2024-07-03 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0011_rename_reward_spin_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spin",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
